fix: implemented the multiple webpack compile config
serverless-heaven/serverless-webpack pull request #537
Opened 2019-09-05 07:37 UTC by RishikeshDarandale

## What did you implement:

Implemented the fix for providing a way to provide the multiple webpack compile configuration in webpack configuration file. The sample config can be seen as below:

```js
// webpack.config.js

module.exports = [
  {
    entry: './handler1.js',
    target: 'node',
    module: {
      loaders: [ ... ],
    },
  },
  {
    entry: './handler2.js',
    target: 'node',
    module: {
      loaders: [ ... ],
    },
  },
];
```

Similarly, webpack configuration can export an `asynchronous object` with multi compile configuration would work as expected.

Closes #439 

## How did you implement it:

This plugin already supports the multi compile configuration when `package.individually` is set to `true`. When there are multiple functions and `package.individually` is set, then provided single webpack configuration gets cloned for function count times.

Thus, if we provide an option to `user` specify the multi webpack compile configuration, then `package.individually` becomes trivial and  probably can not determine that which config from multi set to be used for cloning for all functions.

- `validate` function was expecting a single webapck configuration object.
- Thus, added logic to check if the configuration object is an array or not. If yes, then each config is processed the same way it was done for single configuration object.

When multi webpack compile config is provided, to constraints will be imposed as below:
- `package.individually` should be set to `false`.
- `package.individually` is `false`, thus `output.path` for each config provided **should** match.

Above constraints make sure that post `validate` process such as `compile`, `package`, `local invoke` and `offline` functions behave as it is.

## How can we verify it:

I have verified this with following examples:
- multi-function with multi compile config provided as shown above.
- single function with multi compile config provided as shown above.

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

2019-09-05 13:55 UTC, RishikeshDarandale commented
I will give it a try to resolve the two constraints mentioned above with my solution. Mean time you can provide the feedback for existing changes. Thanks!

2019-09-09 06:53 UTC, RishikeshDarandale commented
@HyperBrain , Can you please review?

2019-09-13 14:12 UTC, RishikeshDarandale commented
@HyperBrain , any comment/update on this?

2019-09-23 07:00 UTC, RishikeshDarandale commented
@HyperBrain, any luck?

2019-11-07 15:20 UTC, RishikeshDarandale commented
@HyperBrain , Sorry to ping you one more time. Did you get a chance to look into this one?

2020-05-10 14:21 UTC, tyrauber commented
:+1: for this fix. I could use it as well.  I've got a webpack.config that builds several different entries, with different outputs and plugins, and serverless with serverless-webpack chokes on `module.export = [server, web, serverless]` with the following error:
```
  Error: Plugin could not be registered at 'before-compile'. Hook was not found.
  BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
```
Any other workarounds?

2020-05-12 17:37 UTC, RishikeshDarandale commented
@tyrauber , if you have your code somewhere on github, then I will take a look. If not passible to share the code, then share the snippet.

2020-05-12 19:05 UTC, tyrauber commented
Hi @RishikeshDarandale, here is a [gist of a Serverless Vue Webpack 4 Config]( https://gist.github.com/tyrauber/88fcd725ab03954b26aeda21be0ee2ca) that details the issue.  The problem comes from wanting to code split and share a base configuration and use webpack-merge to maintain them. Each entry - client, server, serverless - potentially needs different plugins or outputs.  Unfortunately, serverless-webpack chokes on an array of exports, while webpack handles it fine.

2020-05-25 06:11 UTC, RishikeshDarandale commented
@miguel-a-calles-mba Can you please review this wrt `master` or `release/5.3.2`? 

Please see [here](https://github.com/serverless-heaven/serverless-webpack/pull/560#issuecomment-633223042) for more comments on #560 .

2020-05-29 12:52 UTC, RishikeshDarandale commented
@miguel-a-calles-mba , any update on this pull request?

2020-06-02 01:57 UTC, miguel-a-calles-mba commented
@RishikeshDarandale This PR is set for 5.4.0.

2020-06-02 06:52 UTC, RishikeshDarandale commented
sure @miguel-a-calles-mba 

I have rebased my changes with release `5.4.0`locally, but `5.4.0` has an `package` issue. This has to wait till it gets fixed or if you say that it's not an issue, then I can push my rebased changes!

2020-06-21 21:44 UTC, miguel-a-calles-mba commented
@RishikeshDarandale, I resolved the conflicts. Please verify the changes.

2021-01-29 19:16 UTC, j0k3r commented
Sorry I made a mistake while merging `release/5.4.0` into master and removed it. The removal automatically closed that PR. It should now be rebased against the master and fix conflicts.

2021-03-15 16:39 UTC, miguel-a-calles-mba requested changes
Please address the merge conflicts and the failed builds. Thanks.

2021-05-10 19:28 UTC, j0k3r commented
@RishikeshDarandale any chances to rebase against the master, fix conflicts and tests? Thanks 🙏

2021-05-11 04:01 UTC, RishikeshDarandale commented
@j0k3r , let me find some time to check this one. It's a year old change now.

2021-11-21 21:06 UTC, j0k3r commented
Will you have time to update it?

2023-07-24 07:25 UTC, closed without merging